name = "ziran-coin-jule-api"
main = "worker/worker.js"
compatibility_date = "2026-07-26"

[[d1_databases]]
binding = "DB"
database_name = "YOUR_ZIRANCOIN_D1_DATABASE_NAME"
database_id = "YOUR_REAL_D1_DATABASE_UUID"

# Add this Worker route in Cloudflare:
# zirancoin.jsl-ian.com/api/*
#
# Add secret in Cloudflare:
# COIN_API_KEY
