name = "zirancoin"
main = "worker/worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "."
binding = "ASSETS"

[vars]
ALLOWED_ORIGIN = "https://zirancoin.peterjingrn01.workers.dev"

[[d1_databases]]
binding = "SQL_DB"
database_name = "ziran_db"
database_id = "e5547321-9171-450a-8555-22c7ff7d48b7"

[[kv_namespaces]]
binding = "DB"
id = "1156e2611ce5471698ed872f927b9a5f"
