const SUPPLY=1000000000n,SCALE=100000000n;
export default{async fetch(r,e){const u=new URL(r.url),c={"Access-Control-Allow-Origin":e.ALLOWED_ORIGIN||"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};if(r.method==="OPTIONS")return new Response(null,{headers:c});try{let x;if(u.pathname==="/api/health")x={ok:true,service:"ziran2-api"};else if(u.pathname==="/api/signup"&&r.method==="POST")x=await signup(r,e);else if(u.pathname==="/api/signin"&&r.method==="POST")x=await signin(r,e);else if(u.pathname==="/api/me"&&r.method==="GET")x=await me(r,e);else if(u.pathname==="/api/transfer"&&r.method==="POST")x=await transfer(r,e);else if(u.pathname==="/api/explorer")x=await explorer(e);else if(u.pathname==="/api/admin/genesis"&&r.method==="POST")x=await genesis(r,e);else return J({error:"Not found"},404,c);return J(x,200,c)}catch(x){return J({error:x.message||"Request failed"},x.status||400,c)}}};
function J(d,s=200,h={}){return new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store",...h}})}function F(m,s=400){const x=new Error(m);x.status=s;throw x}
const E=v=>String(v||"").trim().toLowerCase(),T=(v,n=160)=>String(v||"").trim().slice(0,n);
function R(n=24){const a=new Uint8Array(n);crypto.getRandomValues(a);return[...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
const B=a=>btoa(String.fromCharCode(...new Uint8Array(a))),UB=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function H(s){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function P(p,s){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]),b=await crypto.subtle.deriveBits({name:"PBKDF2",salt:UB(s),iterations:210000,hash:"SHA-256"},k,256);return B(b)}
function U(v){const s=String(v).trim();if(!/^\d+(\.\d{1,8})?$/.test(s))F("Amount must be positive with no more than 8 decimals.");const[a,b=""]=s.split("."),n=BigInt(a)*SCALE+BigInt((b+"00000000").slice(0,8));if(n<=0n)F("Amount must be greater than zero.");return n}
function U0(v){const[a,b=""]=String(v||"0").split(".");return BigInt(a)*SCALE+BigInt((b+"00000000").slice(0,8))}
function S(n){const a=n/SCALE,b=(n%SCALE).toString().padStart(8,"0").replace(/0+$/,"");return b?`${a}.${b}`:`${a}`}
async function session(e,id){const t=R(32);await e.DB.put(`session:${t}`,String(id),{expirationTtl:604800});return t}
async function auth(r,e){const h=r.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))F("Unauthorized",401);const id=await e.DB.get(`session:${h.slice(7)}`);if(!id)F("Unauthorized",401);const u=await e.SQL_DB.prepare("SELECT * FROM users WHERE id=?").bind(id).first();if(!u)F("Unauthorized",401);return u}
async function signup(r,e){const d=await r.json(),n=T(d.name,80),em=E(d.email),p=String(d.password||"");if(n.length<2)F("Name is required.");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em))F("Valid email required.");if(p.length<10)F("Password must contain at least 10 characters.");if(await e.SQL_DB.prepare("SELECT id FROM users WHERE email=?").bind(em).first())F("Email already registered.",409);const sa=new Uint8Array(16);crypto.getRandomValues(sa);const sb=B(sa),ph=await P(p,sb),pub="ZR-"+R(8).toUpperCase(),pair="PAIR-"+R(16).toUpperCase(),q=await e.SQL_DB.prepare("INSERT INTO users(public_id,pair_id,name,email,password_hash,password_salt) VALUES(?,?,?,?,?,?)").bind(pub,pair,n,em,ph,sb).run();await e.SQL_DB.prepare("INSERT INTO wallets(user_id,balance) VALUES(?,?)").bind(q.meta.last_row_id,"0").run();return{token:await session(e,q.meta.last_row_id),public_id:pub}}
async function signin(r,e){const d=await r.json(),u=await e.SQL_DB.prepare("SELECT * FROM users WHERE email=?").bind(E(d.email)).first();if(!u||await P(String(d.password||""),u.password_salt)!==u.password_hash)F("Incorrect email or password.",401);return{token:await session(e,u.id)}}
async function me(r,e){const u=await auth(r,e),w=await e.SQL_DB.prepare("SELECT balance FROM wallets WHERE user_id=?").bind(u.id).first(),g=await e.SQL_DB.prepare("SELECT total_supply FROM genesis WHERE id=1").first(),l=await e.SQL_DB.prepare("SELECT l.*,cp.email counterparty_email FROM ledger l LEFT JOIN users cp ON cp.id=l.counterparty_user_id WHERE l.user_id=? ORDER BY l.id DESC LIMIT 100").bind(u.id).all();return{user:{name:u.name,email:u.email,public_id:u.public_id,pair_status:u.pair_status},wallet:{balance:w.balance},supply:g?.total_supply||"0",ledger:l.results}}
async function transfer(r,e){const f=await auth(r,e),d=await r.json(),em=E(d.to_email),to=await e.SQL_DB.prepare("SELECT * FROM users WHERE email=?").bind(em).first();if(em===f.email)F("Cannot send to the same account.");if(!to)F("Recipient not found.",404);const a=U(d.amount),at=S(a),fw=await e.SQL_DB.prepare("SELECT balance FROM wallets WHERE user_id=?").bind(f.id).first(),tw=await e.SQL_DB.prepare("SELECT balance FROM wallets WHERE user_id=?").bind(to.id).first(),fb=U0(fw.balance),tb=U0(tw.balance);if(fb<a)F("Insufficient balance.");const id="TX-"+R(20).toUpperCase(),proof=await H([id,f.pair_id,to.pair_id,at,new Date().toISOString()].join("|")),nf=fb-a,nt=tb+a;await e.SQL_DB.batch([e.SQL_DB.prepare("UPDATE wallets SET balance=? WHERE user_id=?").bind(S(nf),f.id),e.SQL_DB.prepare("UPDATE wallets SET balance=? WHERE user_id=?").bind(S(nt),to.id),e.SQL_DB.prepare("INSERT INTO transactions(tx_id,tx_type,from_user_id,to_user_id,amount,memo,pair_proof) VALUES(?,?,?,?,?,?,?)").bind(id,"TRANSFER",f.id,to.id,at,T(d.memo),proof),e.SQL_DB.prepare("INSERT INTO ledger(tx_id,user_id,counterparty_user_id,entry_type,amount,balance_after) VALUES(?,?,?,?,?,?)").bind(id,f.id,to.id,"DEBIT",at,S(nf)),e.SQL_DB.prepare("INSERT INTO ledger(tx_id,user_id,counterparty_user_id,entry_type,amount,balance_after) VALUES(?,?,?,?,?,?)").bind(id,to.id,f.id,"CREDIT",at,S(nt))]);return{ok:true,tx_id:id,pair_proof:proof}}
async function genesis(r,e){const d=await r.json();if(!e.GENESIS_KEY)F("GENESIS_KEY not configured.",500);if(String(d.genesis_key)!==e.GENESIS_KEY)F("Invalid genesis key.",403);if(await e.SQL_DB.prepare("SELECT id FROM genesis WHERE id=1").first())F("Genesis already completed.",409);const o=await e.SQL_DB.prepare("SELECT * FROM users WHERE email=?").bind(E(d.owner_email)).first();if(!o)F("Owner account must exist.",404);const id="GENESIS-"+R(18).toUpperCase(),at=S(SUPPLY*SCALE),proof=await H([id,o.pair_id,at,"GENESIS"].join("|"));await e.SQL_DB.batch([e.SQL_DB.prepare("INSERT INTO genesis(id,tx_id,owner_user_id,total_supply,pair_proof) VALUES(1,?,?,?,?)").bind(id,o.id,at,proof),e.SQL_DB.prepare("UPDATE wallets SET balance=? WHERE user_id=?").bind(at,o.id),e.SQL_DB.prepare("INSERT INTO transactions(tx_id,tx_type,to_user_id,amount,memo,pair_proof) VALUES(?,?,?,?,?,?)").bind(id,"GENESIS",o.id,at,"One-time genesis 1B",proof),e.SQL_DB.prepare("INSERT INTO ledger(tx_id,user_id,entry_type,amount,balance_after) VALUES(?,?,?,?,?)").bind(id,o.id,"CREDIT",at,at)]);return{ok:true,supply:at,tx_id:id,pair_proof:proof}}
async function explorer(e){const g=await e.SQL_DB.prepare("SELECT total_supply FROM genesis WHERE id=1").first(),a=(await e.SQL_DB.prepare("SELECT COUNT(*) n FROM users").first()).n,t=(await e.SQL_DB.prepare("SELECT COUNT(*) n FROM transactions WHERE tx_type='TRANSFER'").first()).n,c=(await e.SQL_DB.prepare("SELECT COALESCE(SUM(CAST(balance AS REAL)),0) n FROM wallets").first()).n,l=await e.SQL_DB.prepare("SELECT t.tx_id,t.amount,t.pair_proof,t.created_at,fu.public_id from_public_id,tu.public_id to_public_id FROM transactions t LEFT JOIN users fu ON fu.id=t.from_user_id JOIN users tu ON tu.id=t.to_user_id ORDER BY t.id DESC LIMIT 50").all();return{supply:g?.total_supply||"0",circulating:String(c),accounts:a,transfers:t,latest:l.results}}
